on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

defaults:
  run:
    shell: bash
    working-directory: ./Netflix

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout changes
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test